version: "3.5"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/stissera/data/wp

  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/stissera/data/db

  bonus:
    name: bonus
    driver: local
    driver_opts:
      type: none
      o: bind
      device: home/stissera/data/bonus

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - stissera
        ports:
      - "3306:3306"

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - stissera
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - stissera
    depends_on:
      - wordpress
    ports:
      - "443:443"

networks:
  stissera:
    name: stissera
    driver: bridge
