version: "3.9"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/stissera/data/wp

  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/stissera/data/db

  bonus:
    name: bonus
    driver: local
    driver_opts:
      type: none
      o: bind
      device: home/stissera/data/bonus

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - stissera
        ports:
      - "3306:3306"

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    env_file: .env
    volumes:
      - wp:/var/www/wordpress
    networks:
      - stissera
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    volumes:
      - wp:/var/www/wordpress
    networks:
      - stissera
    depends_on:
      - wordpress
    ports:
      - "443:443"

  redis:
    container_name: redis
    build: ./requirements/bonus/redis/
    restart: always
    env_file: .env
    networks:
      - stissera
    depends_on:
      - nginx
    ports:
      - "6379:6379"

  ftp-server:
    container_name: ftp-server
    build: ./requirements/bonus/ftp-server/
    restart: always
    env_file: .env
    volumes:
      - wp:/home/bca
    networks:
      - stissera
    depends_on:
      - nginx
    ports:
      - "21:21"
      - "21000-21010:21000-21010"

  site:
    container_name: site
    build: requirements/bonus/site/
    restart: always
    networks:
      - stissera
    depends_on:
      - nginx
    ports:
      - "8081:8081"

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    restart: always
    depends_on:
      - mariadb
    networks:
      - stissera
    ports:
      - "8080:8080"

networks:
  stissera:
    name: stissera
    driver: bridge